### ISSUE TITLE
Project information

### ISSUE THREAD

**Issue by pidgeon777** [yqwu905/cscope-calltree.nvim#1]
Hello, this seems to be an interesting project. Could you kindly provide more details please?

Best regards

**Comment by yqwu905** [comment]
Sorry about that.
This project aim to  generate call hierarchy tree base on **cscope**, since call hierarchy feature is not well supported in most lsp(clangd, for me).
**This project is not yet usable**, its most basic features still need to be developed, maybe in a few weeks.

**Comment by pidgeon777** [comment]
It would be great to have a neovim plugin showing a call-tree of the functions using `cscope`. I think such a plugin doesn't exist, yet. Maybe some existing neovim UI library could be used, like this one:

https://github.com/MunifTanjim/nui.nvim

**Comment by pidgeon777** [comment]
Also yes, `clangd` is missing some call hierarchy functions ([outgoing calls](https://github.com/clangd/clangd/discussions/1206)), so `cscope` could be a good choice.

**Comment by yqwu905** [comment]
I have pushed a initial version, so I think this issue could be closed. Just reopen it if you have any further questions

**Comment by pidgeon777** [comment]
Great! I would suggest you to also post your plugin here:

- https://www.reddit.com/r/neovim/
- https://dotfyle.com/
- https://github.com/rockerBOO/awesome-neovim
